version: '3.3'
services:
  challenge:
    image: challenge:dev
    build:
      context: ../..
      dockerfile: docker/dev/app/Dockerfile
      args:
        - MIX_ENV=dev
    volumes:
      - ../../src:/app/src
      - shared:/shared
      - ../../docker/dev:/docker
    depends_on:
      - db
  db:
    build:
        context: ../..
        dockerfile: docker/dev/db/Dockerfile
    image: mariadb:dev
    volumes:
      - data:/var/lib/mysql
      - shared:/shared
    environment:
        - MYSQL_USER=pyr
        - MYSQL_PASSWORD=pyr
        - MYSQL_HOST=%
        - MYSQL_ROOT_PASSWORD=password1
        - MYSQL_ROOT_HOST=%
volumes:
  data:
  shared:
