#!/bin/sh

# for dev we do deps build/compile at run time since we are importing the volume

################################################
echo "===> starting hello db migrations..."
# npm run create stuff

echo "===> starting hello in dev mode..."
# exec run things here
